apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: app
  name: app
spec:
  type: NodePort          # Cambiar el tipo a NodePort
  ports:
    - name: "3000"
      port: 3000           # El puerto dentro del clúster
      targetPort: 3000      # El puerto que escucha el contenedor de la app
      nodePort: 30000       # El puerto asignado en la máquina local
  selector:
    io.kompose.service: app
